### ISSUE TITLE
Update no-show cancellation_reason_code

### ISSUE THREAD

**Issue by rubenpeters91** [UMCU-Digital-Health/No_Show#83]
Currently we use multiple codes for getting the no-shows from the appointment table. With HiX 6.3 all no-show codes are now reduced to 'N', which can mean both 'Patient niet verschenen (of te laat gemeld)' or 'No show zonder kennisgeving'. To check the difference, see the cancellation_reason_display column in the Appointments table.

Important! Some of the old codes now have a different meaning
- M: now means MDO or 'Geen machtiging verkregen'
- The other codes no longer exist

**Comment by WoltersEric** [comment]
Doublecheck whether 'P' ('Verzoek patient (24 van tevoren afgemeld)') means <24 or >24

**Comment by WoltersEric** [comment]
Query is geupdated
